FROM gcc:13

RUN apt-get update && apt-get install -y libcurl4-openssl-dev

WORKDIR /app

COPY . .

RUN g++ -std=c++17 \
    main.cpp \
    ServerClass/*.cpp \
    LLM_Manager/*.cpp \
    -I./ServerClass \
    -I./LLM_Manager \
    -o ai_chat_server \
    -lcurl \
    -pthread

EXPOSE 8080

CMD ["./ai_chat_server"]