CREATE TABLE IF NOT EXISTS Books (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    author TEXT NOT NULL,
    genre TEXT NOT NULL,
    status TEXT NOT NULL
);
;

INSERT INTO Books (title, author, genre, status) VALUES
('Ancient Secrets', 'Agatha Penman', 'Mystery', 'Available'),
('Chronicles of Stone', 'Agatha Penman', 'Fantasy', 'Available'),
('The Hidden Librarian', 'Stephen Page', 'Sci-Fi', 'Available'),
('Chronicles of Dreams', 'J.R.R. Scribbler', 'Fantasy', 'Available'),
('The Shadow of Silent Wind', 'Agatha Penman', 'History', 'Available'),
('The Shadow of Ancient Dreams', 'J.R.R. Scribbler', 'Mystery', 'Available'),
('Whispers of Dreams', 'J.R.R. Scribbler', 'Fantasy', 'Available'),
('Whispers of Dreams', 'J.R.R. Scribbler', 'History', 'Available'),
('Chronicles of Dreams', 'Stephen Page', 'Fantasy', 'Available'),
('The Ancient Librarian', 'George R.R. Ink', 'Fantasy', 'Available'),
('The Shadow of Ancient Stars', 'J.R.R. Scribbler', 'Mystery', 'Available'),
('The Shadow of Midnight Stars', 'Stephen Page', 'Fantasy', 'Available'),
('Whispers of Dreams', 'Stephen Page', 'Mystery', 'Available'),
('Whispers of Time', 'Stephen Page', 'Sci-Fi', 'Available'),
('The Shadow of Ancient Wind', 'Stephen Page', 'Mystery', 'Available'),
('The Forgotten Librarian', 'George R.R. Ink', 'Mystery', 'Available'),
('Hidden Secrets', 'Agatha Penman', 'Mystery', 'Available'),
('Chronicles of Time', 'J.R.R. Scribbler', 'Sci-Fi', 'Available'),
('Silent Secrets', 'George R.R. Ink', 'Sci-Fi', 'Available'),
('Whispers of Dreams', 'Agatha Penman', 'Sci-Fi', 'Available'),
('Whispers of Dreams', 'Agatha Penman', 'Mystery', 'Available'),
('Whispers of Wind', 'Stephen Page', 'Fantasy', 'Available'),
('Forgotten Secrets', 'J.R.R. Scribbler', 'Mystery', 'Available'),
('Whispers of Time', 'J.R.R. Scribbler', 'Sci-Fi', 'Available'),
('The Midnight Librarian', 'George R.R. Ink', 'History', 'Available'),
('Midnight Secrets', 'Agatha Penman', 'History', 'Available'),
('Whispers of Dreams', 'Stephen Page', 'Fantasy', 'Available'),
('The Shadow of Midnight Dreams', 'J.R.R. Scribbler', 'Mystery', 'Available'),
('Whispers of Dreams', 'J.R.R. Scribbler', 'Fantasy', 'Available'),
('The Hidden Librarian', 'George R.R. Ink', 'Mystery', 'Available'),
('Whispers of Wind', 'Stephen Page', 'History', 'Available'),
('Whispers of Time', 'George R.R. Ink', 'History', 'Available'),
('Whispers of Stars', 'Agatha Penman', 'Mystery', 'Available'),
('Hidden Secrets', 'George R.R. Ink', 'History', 'Available'),
('The Shadow of Midnight Stars', 'Stephen Page', 'Fantasy', 'Available'),
('The Shadow of Silent Stone', 'George R.R. Ink', 'Sci-Fi', 'Available'),
('The Shadow of Forgotten Time', 'J.R.R. Scribbler', 'Fantasy', 'Available'),
('Silent Secrets', 'Agatha Penman', 'Fantasy', 'Available'),
('Chronicles of Stone', 'George R.R. Ink', 'Sci-Fi', 'Available'),
('Whispers of Dreams', 'Agatha Penman', 'Fantasy', 'Available'),
('Chronicles of Time', 'Agatha Penman', 'Fantasy', 'Available'),
('Whispers of Dreams', 'Agatha Penman', 'History', 'Available'),
('The Ancient Librarian', 'Agatha Penman', 'Fantasy', 'Available'),
('The Forgotten Librarian', 'Agatha Penman', 'Sci-Fi', 'Available'),
('The Midnight Librarian', 'Stephen Page', 'Mystery', 'Available'),
('The Ancient Librarian', 'George R.R. Ink', 'History', 'Available'),
('Chronicles of Wind', 'J.R.R. Scribbler', 'Fantasy', 'Available'),
('Midnight Secrets', 'Stephen Page', 'History', 'Available'),
('Forgotten Secrets', 'Stephen Page', 'History', 'Available'),
('Chronicles of Stone', 'Agatha Penman', 'Sci-Fi', 'Available'),
('Whispers of Dreams', 'George R.R. Ink', 'History', 'Available'),
('The Shadow of Forgotten Time', 'Agatha Penman', 'Fantasy', 'Available'),
('Chronicles of Dreams', 'Agatha Penman', 'Mystery', 'Available'),
('The Hidden Librarian', 'J.R.R. Scribbler', 'Fantasy', 'Available'),
('Hidden Secrets', 'Agatha Penman', 'Mystery', 'Available'),
('Chronicles of Wind', 'Stephen Page', 'Mystery', 'Available'),
('The Hidden Librarian', 'George R.R. Ink', 'Sci-Fi', 'Available'),
('Whispers of Dreams', 'Agatha Penman', 'Fantasy', 'Available'),
('The Shadow of Ancient Stars', 'Agatha Penman', 'Mystery', 'Available'),
('Chronicles of Stars', 'Stephen Page', 'History', 'Available'),
('Chronicles of Stars', 'J.R.R. Scribbler', 'History', 'Available'),
('Whispers of Stars', 'Stephen Page', 'Fantasy', 'Available'),
('Chronicles of Time', 'George R.R. Ink', 'History', 'Available'),
('Silent Secrets', 'George R.R. Ink', 'Mystery', 'Available'),
('Chronicles of Stone', 'Agatha Penman', 'Fantasy', 'Available'),
('The Shadow of Forgotten Wind', 'J.R.R. Scribbler', 'Sci-Fi', 'Available'),
('Whispers of Wind', 'Agatha Penman', 'Fantasy', 'Available'),
('Chronicles of Dreams', 'George R.R. Ink', 'Sci-Fi', 'Available'),
('The Shadow of Forgotten Wind', 'Stephen Page', 'Fantasy', 'Available'),
('Whispers of Stone', 'George R.R. Ink', 'Fantasy', 'Available'),
('Whispers of Stone', 'George R.R. Ink', 'Sci-Fi', 'Available'),
('Chronicles of Wind', 'Stephen Page', 'Fantasy', 'Available'),
('Hidden Secrets', 'J.R.R. Scribbler', 'Fantasy', 'Available'),
('Chronicles of Time', 'J.R.R. Scribbler', 'Sci-Fi', 'Available'),
('Chronicles of Time', 'George R.R. Ink', 'Fantasy', 'Available'),
('Forgotten Secrets', 'Agatha Penman', 'Mystery', 'Available'),
('Hidden Secrets', 'Agatha Penman', 'Fantasy', 'Available'),
('The Shadow of Ancient Time', 'Stephen Page', 'Sci-Fi', 'Available'),
('The Shadow of Midnight Wind', 'Stephen Page', 'Fantasy', 'Available'),
('The Ancient Librarian', 'Stephen Page', 'Mystery', 'Available'),
('Chronicles of Time', 'J.R.R. Scribbler', 'History', 'Available'),
('Midnight Secrets', 'Stephen Page', 'Sci-Fi', 'Available'),
('Hidden Secrets', 'Stephen Page', 'History', 'Available'),
('Chronicles of Time', 'Agatha Penman', 'Fantasy', 'Available'),
('Whispers of Dreams', 'J.R.R. Scribbler', 'Fantasy', 'Available'),
('The Shadow of Silent Stars', 'Stephen Page', 'Sci-Fi', 'Available'),
('The Shadow of Ancient Stone', 'Agatha Penman', 'Mystery', 'Available'),
('Silent Secrets', 'J.R.R. Scribbler', 'Sci-Fi', 'Available'),
('Whispers of Stars', 'Agatha Penman', 'Fantasy', 'Available'),
('The Hidden Librarian', 'Stephen Page', 'Sci-Fi', 'Available'),
('Chronicles of Dreams', 'George R.R. Ink', 'Mystery', 'Available'),
('The Shadow of Midnight Wind', 'Agatha Penman', 'Mystery', 'Available'),
('Midnight Secrets', 'Stephen Page', 'Mystery', 'Available'),
('The Shadow of Hidden Wind', 'J.R.R. Scribbler', 'Mystery', 'Available'),
('The Shadow of Silent Time', 'George R.R. Ink', 'Fantasy', 'Available'),
('The Silent Librarian', 'J.R.R. Scribbler', 'History', 'Available'),
('Whispers of Stone', 'Stephen Page', 'History', 'Available'),
('Chronicles of Wind', 'George R.R. Ink', 'History', 'Available'),
('The Hidden Librarian', 'J.R.R. Scribbler', 'Sci-Fi', 'Available'),
('The Silent Librarian', 'J.R.R. Scribbler', 'Fantasy', 'Available');
